import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Header from "@/components/Header/Header";
import Layout from "@/components/Layout/Layout";
import Intro from "@/components/Intro/Index";

const inter = Inter({ subsets: ["latin"] });
import { useAccount } from "wagmi";
import { Text } from "@chakra-ui/react";

export default function Home() {
  function App() {}
  const { address, isConnecting, isDisconnected } = useAccount();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Intro />
      </Layout>
    </>
  );
}
